fix desktop nixos config
nix flake show throws following error, due to nixos.admin module not
available.

git+file:///home/maari/github/nappairam/dendritic?dir=example&rev=f50ced315b9fd04baf9bea2d2f60657e267e4198
├───checks
error:
       … while calling the 'head' builtin
         at /nix/store/qzm4sksyx1q1g872xxkr1160hhqlk9nm-source/lib/attrsets.nix:1696:13:
         1695|           if length values == 1 || pred here (elemAt values 1) (head values) then
         1696|             head values
             |             ^
         1697|           else

       … while evaluating the attribute 'value'
         at /nix/store/qzm4sksyx1q1g872xxkr1160hhqlk9nm-source/lib/modules.nix:1118:7:
         1117|     // {
         1118|       value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |       ^
         1119|       inherit (res.defsFinal') highestPrio;

       … while evaluating the option `flake.checks':

       … while evaluating definitions from `/nix/store/jqh6mdlli84w49fkhswnicx2392gjvkd-source/example/modules/nixos.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'admin' missing
       at /nix/store/jqh6mdlli84w49fkhswnicx2392gjvkd-source/example/modules/desktop.nix:9:7:
            8|     imports = [
            9|       nixos.admin
             |       ^
           10|       nixos.shell